### ISSUE TITLE
Freyja boot command error: cvxpy.error.SolverError: Solver 'ECOS' failed.

### ISSUE THREAD

**Issue by pratibha-kadam** [andersen-lab/Freyja#108]
**Freyja boot command is showing this error and asking to change the solver as verbose.  **

Traceback (most recent call last):
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 194, in boot
    lin_out, constell_out = perform_bootstrap(df_barcodes, mix, depths_,
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/freyja/sample_deconv.py", line 221, in perform_bootstrap
    out = Parallel(n_jobs=n_jobs)(delayed(bootstrap_parallel)(jj0,
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/fmr-nanopore/anaconda3/envs/freyja-env/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.

I am not able to change the solver setting
Please let me know the solution 
Thanks

**Comment by joshuailevy** [comment]
Hi @pratibha-kadam!
It's pretty hard to see what's going on here without a bit more information. Can you provide a few files that demonstrate this problem?

This sort of behavior is known to occur with ```freyja boot``` for samples with lower coverage sometimes, and that may be what's going on.

**Comment by dylanpilz** [comment]
Addressed by #145

**Comment by skunklem** [comment]
Has anyone else noticed this issue resurfacing? I'm having this same error pop up. I ran `freyja update`, so I know I have the latest data, but that didn't fix it. I'd appreciate any troubleshooting thoughts. It seems to work with an old dataset I have from 06_07_2023-00-12, but as soon as I update, it fails.
